AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 450259112618

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: aneilyounis
      AccountId: '450259112618'
      RootEmail: aneil.younis@outlook.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts: !Ref ProductionAccount

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts: !Ref DevelopmentAccount

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts: !Ref SharedAccount

  ProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Production Account
      RootEmail: aneil.younis+production@outlook.com

  DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Development Account
      RootEmail: aneil.younis+dev@outlook.com

  SharedAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Account
      RootEmail: aneil.younis+shared@outlook.com
